pub const VERSION: &'static str = "0.1.0";

pub const LANGS: [&'static str; 30] = [
    "English",
    "ChineseMandarin",
    "Spanish",
    "Hindi",
    "Arabic",
    "Bengali",
    "Portuguese",
    "Russian",
    "Urdu",
    "Indonesian",
    "German",
    "French",
    "Italian",
    "Turkish",
    "Vietnamese",
    "Telugu",
    "Marathi",
    "Tamil",
    "Urdu",
    "Gujarati",
    "Polish",
    "Ukrainian",
    "Malayalam",
    "Kannada",
    "Oriya",
    "Burmese",
    "Panjabi",
    "Chinese",
    "Maithili",
    "Tagalog",
];
